/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/hybrid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hybrid Endpoint */
        post: operations["hybrid_endpoint_api_hybrid_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cases Endpoint */
        get: operations["list_cases_endpoint_api_cases_get"];
        put?: never;
        /** Create Case Endpoint */
        post: operations["create_case_endpoint_api_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case Endpoint */
        get: operations["get_case_endpoint_api_cases__case_id__get"];
        put?: never;
        post?: never;
        /** Delete Case Endpoint */
        delete: operations["delete_case_endpoint_api_cases__case_id__delete"];
        options?: never;
        head?: never;
        /** Update Case Endpoint */
        patch: operations["update_case_endpoint_api_cases__case_id__patch"];
        trace?: never;
    };
    "/api/cases/{case_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Files Endpoint */
        get: operations["list_files_endpoint_api_cases__case_id__files_get"];
        put?: never;
        /** Upload File Endpoint */
        post: operations["upload_file_endpoint_api_cases__case_id__files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Endpoint */
        post: operations["analyze_endpoint_api_cases__case_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Progress Endpoint */
        get: operations["progress_endpoint_api_cases__case_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Findings Endpoint */
        get: operations["findings_endpoint_api_cases__case_id__findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report Endpoint */
        get: operations["report_endpoint_api_cases__case_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/report/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Report Endpoint */
        get: operations["export_report_endpoint_api_cases__case_id__report_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{full_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Spa Fallback
         * @description Serve index.html for all non-API routes (SPA client-side routing).
         */
        get: operations["spa_fallback__full_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisProgress */
        AnalysisProgress: {
            /** Total */
            total: number;
            /** Completed */
            completed: number;
            /** Status */
            status: string;
        };
        /** AnalysisStartedResponse */
        AnalysisStartedResponse: {
            /** Status */
            status: string;
            /** Case Id */
            case_id: string;
        };
        /** Body_upload_file_endpoint_api_cases__case_id__files_post */
        Body_upload_file_endpoint_api_cases__case_id__files_post: {
            /** File */
            file: string;
        };
        /** Case */
        Case: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** @default open */
            status: components["schemas"]["CaseStatus"];
            /** @default low */
            risk_level: components["schemas"]["RiskLevel"];
            /**
             * Cloud Consent
             * @default false
             */
            cloud_consent: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Files */
            files?: components["schemas"]["CaseFile"][];
            /** Findings */
            findings?: components["schemas"]["Finding"][];
        };
        /** CaseFile */
        CaseFile: {
            /** Id */
            id: string;
            /** Case Id */
            case_id: string;
            /** Filename */
            filename: string;
            format: components["schemas"]["FileFormat"];
            /**
             * Message Count
             * @default 0
             */
            message_count: number;
            /**
             * Preview
             * @default
             */
            preview: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * CaseStatus
         * @enum {string}
         */
        CaseStatus: "open" | "analyzing" | "complete";
        /** CreateCaseRequest */
        CreateCaseRequest: {
            /** Name */
            name: string;
        };
        /** DeleteResponse */
        DeleteResponse: {
            /** Ok */
            ok: boolean;
        };
        /**
         * FileFormat
         * @enum {string}
         */
        FileFormat: "whatsapp" | "imessage" | "email" | "plain_text";
        /** Finding */
        Finding: {
            /** Id */
            id: string;
            /** Case Id */
            case_id: string;
            /** File Id */
            file_id: string;
            category: components["schemas"]["FindingCategory"];
            severity: components["schemas"]["Severity"];
            /** Quote */
            quote: string;
            /** Explanation */
            explanation: string;
            /**
             * Source
             * @default local
             */
            source: string;
            /**
             * Chunk Index
             * @default 0
             */
            chunk_index: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * FindingCategory
         * @enum {string}
         */
        FindingCategory: "threat" | "scam" | "abuse" | "pattern" | "timeline_event" | "communication";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Models */
            models: {
                [key: string]: string;
            };
        };
        /** HybridRequest */
        HybridRequest: {
            /** Prompt */
            prompt: string;
            /** Tools */
            tools?: {
                [key: string]: unknown;
            }[] | null;
        };
        /** HybridResponse */
        HybridResponse: {
            /** Function Calls */
            function_calls: {
                [key: string]: unknown;
            }[];
            /** Source */
            source: string;
            /** Confidence */
            confidence: number;
            /** Total Time */
            total_time: number;
        };
        /** Report */
        Report: {
            /** Case Id */
            case_id: string;
            /** Case Name */
            case_name: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Summary */
            summary: string;
            risk_level: components["schemas"]["RiskLevel"];
            /** Timeline */
            timeline: components["schemas"]["TimelineEntry"][];
            /** Findings By Category */
            findings_by_category: {
                [key: string]: components["schemas"]["Finding"][];
            };
            /** Stats */
            stats: {
                [key: string]: number;
            };
            /**
             * Markdown
             * @default
             */
            markdown: string;
        };
        /**
         * RiskLevel
         * @enum {string}
         */
        RiskLevel: "low" | "medium" | "high" | "critical";
        /**
         * Severity
         * @enum {string}
         */
        Severity: "low" | "medium" | "high" | "critical";
        /** TimelineEntry */
        TimelineEntry: {
            /** Date */
            date: string;
            /** Event */
            event: string;
            severity: components["schemas"]["Severity"];
            /** Source File */
            source_file: string;
            /** Quote */
            quote: string;
        };
        /** UpdateCaseRequest */
        UpdateCaseRequest: {
            /** Name */
            name?: string | null;
            /** Cloud Consent */
            cloud_consent?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    hybrid_endpoint_api_hybrid_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HybridRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HybridResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    history_api_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_cases_endpoint_api_cases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"][];
                };
            };
        };
    };
    create_case_endpoint_api_cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCaseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_endpoint_api_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_case_endpoint_api_cases__case_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_case_endpoint_api_cases__case_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCaseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_files_endpoint_api_cases__case_id__files_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseFile"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_file_endpoint_api_cases__case_id__files_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_endpoint_api_cases__case_id__files_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseFile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_endpoint_api_cases__case_id__analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisStartedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    progress_endpoint_api_cases__case_id__progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisProgress"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    findings_endpoint_api_cases__case_id__findings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Finding"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_endpoint_api_cases__case_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_report_endpoint_api_cases__case_id__report_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    spa_fallback__full_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                full_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
